accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "<str:username>/",
        views.UserProfileView.as_view(),
        name="user_profile",
    ),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField()


class FriendShip(models.Model):
    following = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="follower")
    follower = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="following")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["following", "follower"], name="follow_unique"),
        ]

tweets/models.py
from django.conf import settings
from django.db import models


class Tweet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content


class Like(models.Model):
    target = models.ForeignKey(Tweet, related_name="likes", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="likes", on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["target", "user"], name="like_unique"),
        ]

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email")

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseBadRequest
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, View

from tweets.models import Like, Tweet

from .forms import SignupForm
from .models import FriendShip

User = get_user_model()


class SignupView(CreateView):
    form_class = SignupForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password1"]
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        return response


class UserProfileView(LoginRequiredMixin, DetailView):
    template_name = "accounts/profile.html"
    model = User
    context_object_name = "user"
    slug_url_kwarg = "username"
    slug_field = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        tweets = Tweet.objects.select_related("user").prefetch_related("likes").filter(user=user)
        context["tweet_list"] = tweets.order_by("-created_at")
        context["is_following"] = FriendShip.objects.filter(following=user, follower=self.request.user).exists()
        context["following_num"] = FriendShip.objects.filter(follower=user).count()
        context["followers_num"] = FriendShip.objects.filter(following=user).count()
        likes = Like.objects.filter(user=self.request.user).values_list("target", flat=True)
        context["user_like_list"] = likes
        return context


class FollowView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        following = get_object_or_404(User, username=self.kwargs["username"])
        follower = request.user

        if following == follower:
            messages.warning(request, "自分自身はフォローできません。")
            return HttpResponseBadRequest(render(request, "error/400.html"))

        if FriendShip.objects.filter(following=following, follower=follower).exists():
            messages.warning(request, "フォロー済です。")
            return HttpResponseRedirect(reverse("accounts:user_profile", kwargs={"username": following.username}))

        FriendShip.objects.create(following=following, follower=follower)
        return HttpResponseRedirect(reverse("accounts:user_profile", kwargs={"username": following.username}))


class UnFollowView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        following = get_object_or_404(User, username=self.kwargs["username"])
        follower = request.user
        unfollow = FriendShip.objects.filter(following=following, follower=follower)

        if following == follower:
            messages.warning(request, "自分自身を対象には出来ません。")
            return HttpResponseBadRequest(render(request, "error/400.html"))
        elif unfollow.exists():
            unfollow.delete()
            return HttpResponseRedirect(reverse("accounts:user_profile", kwargs={"username": following.username}))
        else:
            messages.warning(request, "無効な操作です。")
            return HttpResponseBadRequest(render(request, "error/400.html"))


class FollowingListView(LoginRequiredMixin, ListView):
    template_name = "accounts/following_list.html"
    context_object_name = "following_list"

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs["username"])
        return FriendShip.objects.select_related("following").filter(follower=user).order_by("-created_at")


class FollowerListView(LoginRequiredMixin, ListView):
    template_name = "accounts/follower_list.html"
    context_object_name = "follower_list"

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs["username"])
        return FriendShip.objects.select_related("follower").filter(following=user).order_by("-created_at")

templates/accounts/follower_list.html
{% extends "base.html" %}

{% block title %}Followers{% endblock %}

{% block content %}
<h1>フォロワー一覧</h1>
{% if follower_list %}
{% for follower in follower_list %}
<div>
    <a href="{% url 'accounts:user_profile' username=follower.follower.username %}" class="links">
        {{ follower.follower }}
    </a>
</div>
{% endfor %}
{% else %}
<p>フォロワーはいません。</p>
{% endif %}
<button class="blueback">
    <a href="{{request.META.HTTP_REFERER}}">
        戻る
    </a>
</button>
{% endblock %}

templates/accounts/following_list.html
{% extends "base.html" %}

{% block title %}followings{% endblock %}

{% block content %}
<h1>フォロー一覧</h1>
{% if following_list %}
{% for following in following_list %}
<div>
    <a href="{% url 'accounts:user_profile' username=following.following.username %}" class="links">
        {{ following.following }}
    </a>
</div>
{% endfor %}
{% else %}
<p>フォローしているユーザーはいません。</p>
{% endif %}
<button class="blueback">
    <a href="{{request.META.HTTP_REFERER}}">
        戻る
    </a>
</button>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}Log In{% endblock %}

{% block content %}
<h1>ログイン</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="blueback">ログイン</button>
</form>
{% endblock %}

templates/accounts/logout.html
{% extends "base.html" %}

{%load static %}

<link rel="stylesheet" href="{% static 'css/twitterclone.css' %}">

{% block title %}Log Out{% endblock %}

{% block content %}
<p>ログアウトしました。</p>
{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}
<h1>Profile</h1>
{% for message in messages %}
<div>{{ message }}</div>
{% endfor %}
<p>{{ user.username }}</p>
<div id="profmid">
    {% if request.user != user %}
    {% if is_following is True %}
    <form action="{% url 'accounts:unfollow' user.username %}" method="POST">
        <button type="submit" id="unfollow">アンフォロー</button>
        {% csrf_token %}
    </form>
    {% else %}
    <form action="{% url 'accounts:follow' user.username %}" method="POST">
        <button type="submit" id="follow">フォロー</button>
        {% csrf_token %}
    </form>
    {% endif %}
    {% endif %}
    <p>フォロー数:<a href="{% url 'accounts:following_list' user.username %}" class="links">{{ following_num }}</a></p>
    <p>フォロワー数:<a href="{% url 'accounts:follower_list' user.username %}" class="links">{{ followers_num }}</a></p>
</div>
{% for tweet in tweet_list %}
<div class="tweetbox">
    <ul class="topbar">
        <li>
            <a href="{% url 'accounts:user_profile' username=tweet.user %}">
                {{ tweet.user }}
            </a>
        </li>
        <li>
            <p>{{ tweet.created_at }}</p>
        </li>
    </ul>
    <p class="contents">{{ tweet.content | linebreaksbr }}</p>
    <ul class="buttombar">
        <li>
            <a href="{% url 'tweets:detail' tweet.pk %}">
                <i class="bi bi-eye-fill"></i>
            </a>
        </li>
        {% if request.user == tweet.user %}
        <li>
            <a href="{% url 'tweets:delete' tweet.pk %}">
                <i class="bi bi-trash-fill"></i>
            </a>
        </li>
        {% endif %}
        {% include 'tweets/like.html' %}
    </ul>
</div>
{% endfor %}
<button class="blueback">
    <a href="{% url 'tweets:home' %}">
        ホームへ
    </a>
</button>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}

{%load static %}

<link rel="stylesheet" href="{% static 'css/twitterclone.css' %}">

{% block title %}Sign Up{% endblock %}

{% block content %}
<h1>ユーザー登録</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="blueback">ユーザー登録</button>
</form>
{% endblock %}