accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "<str:username>/",
        views.UserProfileView.as_view(),
        name="user_profile",
    ),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

tweets/models.py
from django.conf import settings
from django.db import models


class Tweet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content


class Like(models.Model):
    target = models.ForeignKey(Tweet, related_name="likes", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="likes", on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["target", "user"], name="like_unique"),
        ]

tweets/forms.py
from django.forms import ModelForm

from .models import Tweet


class TweetForm(ModelForm):
    class Meta:
        model = Tweet
        fields = ("content",)

tweets/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, View

from .forms import TweetForm
from .models import Like, Tweet

User = get_user_model()


class HomeView(LoginRequiredMixin, ListView):
    template_name = "tweets/home.html"
    model = Tweet
    queryset = model.objects.select_related("user").prefetch_related("likes").order_by("-created_at")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        likes = Like.objects.select_related("target").filter(user=self.request.user).values_list("target", flat=True)
        context["user_like_list"] = likes
        return context


class TweetCreateView(LoginRequiredMixin, CreateView):
    template_name = "tweets/create.html"
    success_url = reverse_lazy("tweets:home")
    form_class = TweetForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TweetDetailView(LoginRequiredMixin, DetailView):
    template_name = "tweets/detail.html"
    model = Tweet
    queryset = model.objects.select_related("user").prefetch_related("likes")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_liked"] = self.object.likes.filter(user=self.request.user, target_id=self.kwargs["pk"]).exists()
        context["liked_count"] = self.object.likes.filter(target_id=self.kwargs["pk"]).count()
        return context


class TweetDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = "tweets/delete.html"
    model = Tweet
    queryset = model.objects.select_related("user")
    success_url = reverse_lazy("tweets:home")

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def test_func(self):
        self.object = self.get_object()
        return self.request.user == self.object.user


class LikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user = request.user
        tweet = get_object_or_404(Tweet, pk=kwargs["pk"])
        Like.objects.get_or_create(target=tweet, user=user)
        likes_count = Like.objects.filter(target=tweet).count()
        context = {"liked_count": likes_count}
        return JsonResponse(context)


class UnlikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user = request.user
        tweet = get_object_or_404(Tweet, pk=kwargs["pk"])
        like = Like.objects.filter(target=tweet, user=user)
        like.delete()
        likes_count = Like.objects.prefetch_related("target").filter(target=tweet).count()
        context = {"liked_count": likes_count}
        return JsonResponse(context)

templates/tweets/create.html
{% extends "base.html" %}

{% block title %}Tweet Create{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="blueback">投稿</button>
</form>
{% endblock %}

templates/tweets/delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>この操作は取り消せません。削除してもよろしいですか？</p>
    <button type="submit" class="blueback">削除</button>
</form>
{% endblock %}

templates/tweets/detail.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<p>ユーザー:{{ tweet.user }}</p>
<p>投稿日:{{ tweet.created_at }}</p>
<p>内容:{{ tweet.content }}</p>
{% include 'tweets/like.html' %}

{% if tweet.user == request.user %}
<a href="{% url 'tweets:delete' tweet.pk %}">
    <button type="button" class="blueback">削除</button>
</a>
{% endif %}
<a href="{% url 'tweets:home' %}">
    <button type="button" class="whiteback">ホームへ</button>
</a>

{% endblock %}

templates/tweets/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<h1>Home</h1>
<a href="{% url 'tweets:create' %}">
    <i class="bi bi-plus-square"></i>
</a>
{% for tweet in tweet_list %}
<div class="tweetbox">
    <ul class="topbar">
        <li>
            <a href="{% url 'accounts:user_profile' username=tweet.user %}">
                {{ tweet.user }}
            </a>
        </li>
        <li>
            <p>{{ tweet.created_at }}</p>
        </li>
    </ul>
    <p class="contents">{{ tweet.content | linebreaksbr }}</p>
    <ul class="buttombar">
        <li>
            <a href="{% url 'tweets:detail' tweet.pk %}">
                <i class="bi bi-eye-fill"></i>
            </a>
        </li>
        {% if request.user == tweet.user %}
        <li>
            <a href="{% url 'tweets:delete' tweet.pk %}">
                <i class="bi bi-trash-fill"></i>
            </a>
        </li>
        {% endif %}
        {% include 'tweets/like.html' %}
    </ul>
</div>
{% endfor %}
{% endblock %}

templates/tweets/like.html
<div>
    {% if is_liked or tweet.id in user_like_list %}
    <button id="tweet-{{tweet.id}}" class="like_btn" data-url="{% url 'tweets:unlike' tweet.id %}" data-pk={{tweet.pk}}
        data-is-liked="true">
        <i class="bi bi-heart-fill"></i>
    </button>
    {% else %}
    <button id="tweet-{{tweet.id}}" class="like_btn" data-url="{% url 'tweets:like' tweet.id %}" data-pk={{tweet.pk}}
        data-is-liked="false">
        <i class="bi bi-heart"></i>
    </button>
    {% endif %}

    <span id="count_{{tweet.id}}">{{ tweet.likes.count }}</span>
</div>