accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "<str:username>/",
        views.UserProfileView.as_view(),
        name="user_profile",
    ),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<link rel="stylesheet" href="{% static 'css/twitterclone.css' %}">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}Twitter Clone{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
</head>

<body>
  <header>
    {% if request.user.is_authenticated %}
    <a href="{% url 'tweets:home' %}" id="homelink">
      Twitter Clone
    </a>
    <ul class="top">
      <li>
        <a href="{% url 'accounts:logout' %}">
          <button type="button" class="topbuttons whiteback">Logout</button>
        </a>
      </li>
      <li>
        <a href="{% url 'accounts:user_profile' username=request.user.username %}" id="usericon">
          {{ request.user.username }}
        </a>
      </li>
    </ul>
    {% else %}
    <p id="logo">Twitter Clone</p>
    <ul class="top">
      <li>
        <a href="{% url 'accounts:login' %}">
          <button type="button" class="topbuttons whiteback">ログイン</button>
        </a>
      </li>
      <li>
        <a href="{% url 'accounts:signup' %}">
          <button type="button" class="topbuttons blueback">登録</button>
        </a>
      </li>
    </ul>
    {% endif %}
  </header>
  {% block content %}
  {% endblock %}
  {% include 'scripts.html' %}
</body>

</html>

templates/scripts.html
<script>
    for (const LikeBtn of document.getElementsByClassName('like_btn')) {

        LikeBtn.addEventListener('click',
            async () => {
                const isLiked = LikeBtn.dataset.isLiked === 'true'
                const response = await fetch(
                    `/tweets/${LikeBtn.dataset.pk}/${isLiked ? 'unlike' : 'like'}/`,
                    { method: 'POST', headers: { 'X-CSRFToken': '{{ csrf_token }}' } },
                )
                const data = await response.json()
                LikeBtn.innerHTML = isLiked ? '<i class="bi bi-heart"></i>' : '<i class="bi bi-heart-fill"></i>'
                LikeBtn.dataset.isLiked = isLiked ? 'false' : 'true'
                const LikeDisplay = document.querySelector("#count_" + LikeBtn.dataset.pk)
                LikeDisplay.innerHTML = String(data.liked_count)
            }
        )
    }
</script>